my_string =input("Ваш текст: ")
print("В вашем тексте" ,len(my_string) , "букв")
my_string = int(input('год: ' .upper()))
print(my_string)
my_string = str(input("МЕСЯЦ: " .lower()))
print(my_string)
my_string = input("В чём смысл бытия?: " .replace(" ",""))
print(my_string)
my_string = ("Привет")
print(my_string [0])
my_string = ("Пока")
print(my_string [3])